# Generated by Django 3.1.2 on 2020-10-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('item_range_min', models.IntegerField()),
                ('item_range_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('photo_front', models.URLField()),
                ('photo_back', models.URLField()),
                ('price', models.FloatField()),
                ('has_it_been_sold', models.BooleanField()),
                ('item_number', models.IntegerField(unique=True)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmestore.category')),
            ],
        ),
    ]
