# Generated by Django 3.1.2 on 2020-11-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mmestore", "0002_remove_craftitem_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftitem",
            name="photo_back_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="craftitem",
            name="photo_back_width",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="craftitem",
            name="photo_front_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="craftitem",
            name="photo_front_width",
            field=models.IntegerField(null=True),
        ),
    ]
