# Generated by Django 3.1.2 on 2020-11-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mmestore", "0005_auto_20201031_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craftitem",
            name="item_number",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
