# Generated by Django 3.1.2 on 2020-11-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmestore', '0006_auto_20201031_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftitem',
            name='dress_size',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
