# Generated by Django 3.2.4 on 2021-08-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmestore', '0012_alter_craftitem_pay_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftitem',
            name='shipping',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
