# Generated by Django 3.2.4 on 2021-08-14 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmestore', '0015_auto_20210805_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftfair',
            name='first_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='craftfair',
            name='first_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
