# Generated by Django 3.2.7 on 2021-09-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mmestore", "0017_alter_craftfair_photo_fair"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftitem",
            name="craft_fair",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mmestore.craftfair",
            ),
        ),
    ]
