# Generated by Django 3.2.7 on 2021-09-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmestore', '0021_alter_craftitem_craft_fair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftitem',
            name='craft_fair',
        ),
    ]
