# Generated by Django 4.0 on 2021-12-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mmestore", "0023_craftitem_craft_fair"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cat_code",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
